Social Bookmarking Platform/Models/Bookmark.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Social_Bookmarking_Platform.Models
{
    public class Bookmark
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Titlul este obligatoriu")]
        [StringLength(100, ErrorMessage = "Titlul nu poate avea mai mult de 100 de caractere")]
        public string Title { get; set; }
        public int Likes { get; set; } = 0;
        public DateTime Date { get; set; }

        [Required(ErrorMessage = "Categoria este obligatorie")]
        public int? CategoryId { get; set; }

        public string? UserId { get; set; }

        public virtual Category? Category { get; set; }

        public virtual ApplicationUser? User { get; set; }

        public virtual ICollection<Comment>? Comments { get; set; }

        public virtual ICollection<BookmarkBoard>? BookmarkBoards { get; set; }

        [NotMapped]
        public IEnumerable<SelectListItem>? Categ { get; set; }
    }
}

Social Bookmarking Platform/Controllers/BookmarksController.cs
using Ganss.Xss;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Social_Bookmarking_Platform.Data;
using Social_Bookmarking_Platform.Data.Migrations;
using Social_Bookmarking_Platform.Models;

namespace Social_Bookmarking_Platform.Controllers
{
    public class BookmarksController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public BookmarksController(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager
        )
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        [Authorize(Roles = "User,Admin")]
        public IActionResult Index()
        {
            var userId = _userManager.GetUserId(User);
            var bookmarks = db.Bookmarks
                 .Include("Category")
                 .Include("User")
                 .Where(a => a.UserId == userId)
                 .OrderByDescending(a => a.Date);

            ViewBag.Bookmarks = bookmarks;



            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
                ViewBag.Alert = TempData["messageType"];
            }

            // MOTOR DE CAUTARE
            var search = "";
            if (Convert.ToString(HttpContext.Request.Query["search"]) != null)
            {
                search = Convert.ToString(HttpContext.Request.Query["search"]).Trim(); // eliminam spatiile libere 
                // Cautare in articol (Title)
                List<int> bookmarkIds = db.Bookmarks.Where
                                        (
                                         bk => bk.Title.Contains(search)
                                         //|| bk.Content.Contains(search)
                                        ).Select(a => a.Id).ToList();
                
                // Cautare in comentarii (Content)
                List<int> bookmarkIdsOfCommentsWithSearchString = db.Comments
                                        .Where
                                        (
                                         c => c.Content.Contains(search)
                                        ).Select(c => (int)c.BookmarkId).ToList();
                

                // Se formeaza o singura lista formata din toate id-urile selectate anterior
                List<int> mergedIds = bookmarkIds.Union(bookmarkIdsOfCommentsWithSearchString).ToList();


                // Lista bookmark-urilor care contin cuvantul cautat
                // fie in articol -> Title si Content
                // fie in comentarii -> Content
                bookmarks = db.Bookmarks.Where(bookmark => mergedIds.Contains(bookmark.Id))
                                      .Include("Category")
                                      .Include("User")
                                      .OrderByDescending(a => a.Date);

            }

            ViewBag.SearchString = search;

            // AFISARE PAGINATA

            // Alegem sa afisam 3 articole pe pagina
            int _perPage = 6;

            // Fiind un numar variabil de bookmarks, verificam de fiecare data utilizand 
            // metoda Count()

            int totalItems = bookmarks.Count();

            var currentPage = Convert.ToInt32(HttpContext.Request.Query["page"]);

            // Pentru prima pagina offsetul o sa fie zero
            // Pentru pagina 2 o sa fie 3 
            // Asadar offsetul este egal cu numarul de bookmarks care au fost deja afisate pe paginile anterioare
            var offset = 0;

            // Se calculeaza offsetul in functie de numarul paginii la care suntem
            if (!currentPage.Equals(0))
            {
                offset = (currentPage - 1) * _perPage;
            }

            var paginatedBookmarks = bookmarks.Skip(offset).Take(_perPage);

            // Preluam numarul ultimei pagini
            ViewBag.lastPage = Math.Ceiling((float)totalItems / (float)_perPage);

            // Trimitem bookmarks cu ajutorul unui ViewBag catre View-ul corespunzator
            ViewBag.Bookmarks = paginatedBookmarks;


            if (search != "")
            {
                ViewBag.PaginationBaseUrl = "/Bookmarks/Index/?search=" + search + "&page";
            }
            else
            {
                ViewBag.PaginationBaseUrl = "/Bookmarks/Index/?page";
            }

            return View();
        }

        [HttpPost]
        public IActionResult IncrementLike(int bookmarkId)
        {
            var bookmark = db.Bookmarks.Where(bk => bk.Id == bookmarkId).FirstOrDefault();

            if (bookmark == null)
            {
                TempData["message"] = "Bookmark not found.";
                TempData["messageType"] = "alert-danger";
                return RedirectToAction("Index");
            }

            // Verifică dacă like-ul este mai mare de 0
            if (bookmark.Likes == null)
            {
                bookmark.Likes = 0;  // Setează la 0 dacă este null
            }

            // Alternarea între incrementare și decrementare
            if (bookmark.Likes > 0)
            {
                bookmark.Likes--;  // Scade un like
            }
            else
            {
                bookmark.Likes++;  // Dacă likes sunt 0, le crește
            }

            db.SaveChanges(); // Salvează schimbările

            // După modificare, redirecționează înapoi la pagina Show
            return RedirectToAction("Show", new { id = bookmarkId });
        }



        [Authorize(Roles = "User,Admin")]
        public IActionResult Show(int id)
        {
            Bookmark bookmark = db.Bookmarks.Include("Category")
                                         .Include("Comments")
                                         .Include("User")
                                         .Include("Comments.User")
                              .Where(art => art.Id == id)
                              .First();
            
            // Adaugam board-urile utilizatorului pentru dropdown
            ViewBag.UserBoards = db.Boards
                                      .Where(b => b.UserId == _userManager.GetUserId(User))
                                      .ToList();
          
            SetAccessRights();
            

            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
                ViewBag.Alert = TempData["messageType"];
            }

            return View(bookmark);
        }

        [Authorize(Roles = "User,Admin")]
        public IActionResult New()
        {
            Bookmark bookmark = new Bookmark();

            bookmark.Categ = GetAllCategories();

            return View(bookmark);
        }

        [HttpPost]
        [Authorize(Roles = "User,Admin")]
        public IActionResult Show([FromForm] Comment comment)
        {
            comment.Date = DateTime.Now;

            comment.UserId = _userManager.GetUserId(User);

            if (ModelState.IsValid)
            {
                db.Comments.Add(comment);
                db.SaveChanges();
                return Redirect("/Bookmarks/Show/" + comment.BookmarkId);
            }
            else
            {
                Bookmark bk = db.Bookmarks.Include("Category")
                                         .Include("User")
                                         .Include("Comments")
                                         .Include("Comments.User")
                                         .Where(bk => bk.Id == comment.BookmarkId)
                                         .First();
                
                ViewBag.UserBoards = db.Boards
                                          .Where(b => b.UserId == _userManager.GetUserId(User))
                                          .ToList();
                
                SetAccessRights();

                return View(bk);
            }
        }

        [HttpPost]
        [Authorize(Roles = "User,Admin")]
        public IActionResult New(Bookmark bookmark)
        {
            var sanitizer = new HtmlSanitizer();

            bookmark.Date = DateTime.Now;

            bookmark.UserId = _userManager.GetUserId(User);

            if (ModelState.IsValid)
            {
                //bookmark.Content = sanitizer.Sanitize(bookmark.Content);

                db.Bookmarks.Add(bookmark);
                db.SaveChanges();
                TempData["message"] = "Bookmark-ul a fost adaugat";
                TempData["messageType"] = "alert-success";
                return RedirectToAction("Index");
            }
            else
            {
                bookmark.Categ = GetAllCategories();
                return View(bookmark);
            }
        }

        [HttpPost]
        [Authorize(Roles = "User,Admin")]
        public IActionResult AddBoard([FromForm] BookmarkBoard bookmarkBoard)
        {
            if (ModelState.IsValid)
            {
                // Verificam daca avem deja bookmark-ul in colectie
                if (db.BookmarkBoards
                    .Where(ab => ab.BookmarkId == bookmarkBoard.BookmarkId)
                    .Where(ab => ab.BoardId == bookmarkBoard.BoardId)
                    .Count() > 0)
                {
                    TempData["message"] = "Acest bookmark este deja adaugat in colectie";

Social Bookmarking Platform/Views/Bookmarks/Edit.cshtml
@model Social_Bookmarking_Platform.Models.Bookmark

<h2 class="text-center mt-5">Editare bookmark</h2>

<br />

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-3">

            <form method="post" asp-action="Edit" asp-controller="Bookmarks" asp-route-id="@Model.Id">

                <div asp-validation-summary="All" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Title" class="form-label">Titlu Bookmark-ului</label>
                    <br />
                    <input asp-for="Title" class="form-control" />

                    <span asp-validation-for="Title" class="text-danger"></span>

                    <br /><br />
                </div>

                <div class="form-group">
                    <label for="CategoryId">Selectati categoria</label>
                    <br />
                    <select asp-for="CategoryId" asp-items="Model.Categ" class="form-control">
                        <option value="">Selectati categoria</option>
                    </select>

                    <span asp-validation-for="CategoryId" class="text-danger"></span>

                    <br />
                </div>

                <button class="btn btn-sm btn-success" type="submit">Modifica bookmark</button>

            </form>
        </div>
    </div>
</div>

Social Bookmarking Platform/Views/Bookmarks/Index.cshtml
<br />
<h2 class="text-center">Afisare bookmarks</h2>
<br />

@if (ViewBag.Message != null)
{
    <div class="alert-success p-3 rounded-3 text-center mb-5 @ViewBag.Alert">
        @ViewBag.Message
    </div>
}

<br />

@* Motorul de cautare *@
<form method="GET">
    <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Search topics or keywords" name="search"
               value="@ViewBag.SearchString">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </div>
</form>


@foreach (var bookmark in ViewBag.Bookmarks)
{
    <div class="card">

        <partial name="BookmarkInfo" model="bookmark"></partial>
       
        <a class="btn btn-success" asp-controller="Bookmarks" asp-action="Show" asp-route-id="@bookmark.Id">Afisare bookmark</a>

    </div>

    <br />
    <br />
}


@* Afisarea paginata a articolelor *@
<div>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item">
                <a class="page-link" href="@ViewBag.PaginationBaseUrl=1" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

            @for (int i = 1; i <= ViewBag.lastPage; i++)
            {
                <li class="page-item"> <a class="page-link" href="@ViewBag.PaginationBaseUrl=@i">@(i)</a> </li>
            }

            <li class="page-item">
                <a class="page-link" href="@ViewBag.PaginationBaseUrl=@(ViewBag.lastPage)" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

Social Bookmarking Platform/Views/Bookmarks/New.cshtml
@model Social_Bookmarking_Platform.Models.Bookmark

<h2 class="text-center mt-5">Adaugare bookmark</h2>
<br />
<div class="container mt-5">
    <div class="row">
        <div class="col-6 offset-3">

            <form method="post" asp-action="New" asp-controller="Bookmarks">

                <div asp-validation-summary="All" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Title" class="form-label">Titlu Bookmark</label>
                    <br />
                    <input asp-for="Title" class="form-control" />

                    <span asp-validation-for="Title" class="text-danger"></span>

                    <br /><br />
                </div>
                <!--
                <div class="form-group">
                    <label asp-for="Content" class="form-label">Continut Articol</label>
                    <br />
                    <textarea asp-for="Content" class="form-control summernote"></textarea>

                    <span asp-validation-for="Content" class="text-danger"></span>

                    <br /><br />
                </div>
                -->

                <div class="form-group">
                    <label for="CategoryId">Selectati categoria</label>
                    <br />
                    <select asp-for="CategoryId" asp-items="Model.Categ" class="form-control">
                        <option value="">Selectati categoria</option>
                    </select>

                    <span asp-validation-for="CategoryId" class="text-danger"></span>

                    <br />
                </div>
                <br />
                <button class="btn btn-success" type="submit">Adauga bookmark</button>

            </form>
        </div>
    </div>
</div>

Social Bookmarking Platform/Views/Bookmarks/Show.cshtml
@model Social_Bookmarking_Platform.Models.Bookmark

@if (TempData["message"] != null)
{
    <div class="alert @ViewBag.Alert p-3 rounded-3 text-center mb-5">
        @ViewBag.Message
    </div>
}
<br />

<div class="card">

    <partial name="BookmarkInfo" model="Model"></partial>
        <!--Lipseste ceva aici-->
        <div class="d-flex flex-row justify-content-between">

            <a class="btn btn-success" asp-controller="Bookmarks" asp-action="Edit" asp-route-id="@Model.Id">Editeaza articol</a>
        <form method="post" asp-controller="Bookmarks" asp-action="IncrementLike" asp-route-bookmarkId="@Model.Id">
            <button type="submit" class="btn btn-primary">
                Like <span class="badge bg-secondary">@Model.Likes</span>
            </button>
        </form>
            <form method="post" asp-controller="Bookmarks" asp-action="Delete" asp-route-id="@Model.Id">

                <button class="btn btn-danger" type="submit">Sterge articol</button>

            </form>

        </div>
    
        
    <form method="post" asp-controller="Bookmarks" asp-action="AddBoard">
        <input type="hidden" name="BookmarkId" value="@Model.Id" />
        <div class="d-flex flex-row justify-content-center p-3 border-1 border-top">
            <div>
                <select name="BoardId" class="form-control">
                    <option selected>Adauga acest articol intr-o colectie</option>
                    @foreach (var board in ViewBag.UserBoards)
                    {
                        <option value="@board.Id">@board.Title</option>
                    }
                </select>
            </div>
            <div>
                <input type="submit" class="btn btn-success alert-success" value="+" />
            </div>
        </div>
    </form>
    

</div>

<br />
<br />

@foreach (var comm in Model.Comments)
{
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>

            <div class="col-md-8">

                <div>

                    <p>@comm.Content</p>
                    <small>@comm.Date</small>
                    <strong><i class="bi bi-person"> @comm.User.UserName</i></strong>

                </div>
                <br>

                @if (comm.UserId == ViewBag.UserCurent || ViewBag.EsteAdmin == true)
                {
                    <div class="d-flex">
                        <div>
                            <a class="btn btn-outline-primary" asp-controller="Comments" asp-action="Edit" asp-route-id="@comm.Id">
                                <i class="bi bi-pencil-square"></i> Editeaza
                            </a>

                        </div>
                        <div>
                            <form method="post" asp-controller="Comments" asp-action="Delete" asp-route-id="@comm.Id">

                                <button class="btn btn-outline-danger" type="submit"><i class="bi bi-trash"></i>Sterge</button>

                            </form>
                        </div>
                    </div>
                }

                <br />
            </div>

            <div class="col-md-2"></div>

        </div>

    </div>
}


@* Afisarea formularului in care se poate adauga un comentariu *@

<div class="container">

    <div class="row">

        <div class="col-md-2"></div>

        <div class="col-md-8">

            <div class="card">

                <form method="post" asp-controller="Bookmarks" asp-action="Show">

                    <div class="card-body">

                        <input type="hidden" name="BookmarkId" value="@Model.Id" />

                        <label>Continut comentariu</label>
                        <textarea class="form-control" name="Content"></textarea>
                        <!--
                        <span asp-validation-for="Content" class="text-danger"></span>
                        -->
                        <br /><br />

                        <button class="btn btn-success" type="submit">Adauga comentariul</button>

                    </div>

                </form>

            </div>

        </div>

        <div class="col-md-2"></div>

    </div>

</div>